"""add full_text to papers

Revision ID: 310273937f5f
Revises: bd88c0f3411e
Create Date: 2026-08-20 16:50:31.803295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310273937f5f'
down_revision: Union[str, Sequence[str], None] = 'bd88c0f3411e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('full_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'full_text')
    # ### end Alembic commands ###
